
build_release:
  stage: build
  image: gitlab-lodz.ekoenergetyka.com.pl:5000/eko/dockerimagestm32:build.3
  script:
      - stm32cubeide --launcher.suppressErrors -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild -build STM32G4_unitTests/Release -importAll "$PWD" -data /workspace -printErrorMarkers -I /usr/bin/ --launcher.ini /opt/st/stm32cubeide_1.16.0/stm32cubeide.ini
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_SHORT_SHA}"
    paths:
      - ./Release/STM32G4_unitTests.bin
    expire_in: 1 mos
    access: 'developer'

test_ceedling:
  stage: test
  image: throwtheswitch/madsciencelab:0.3.2
  script:
    - cd tests/ceedling && ceedling